version: 2
jobs:
  build:
    working_directory: ~/laika-react
    docker:
      - image: "circleci/node:12.9.1"
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: install dependencies
        command: make install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
      - run:
        name: lint
        command: make lint
      - run:
        name: test
        command: make test
